### ISSUE TITLE
Exception in thread "main" java.sql.SQLException: No suitable driver found for jdbc:derby://localhost:1527/MotorPartShopDB

### ISSUE THREAD

**Issue by mohite-abhi** [riteshzd/MotorPart-Shop-Software#1]
I am using netbeans on linux and have tried to add the mysql-connector-java.jar by various methods, but still i am getting this error. Do I need to do something else?

The complete error message is :

```
Exception in thread "main" java.sql.SQLException: No suitable driver found for jdbc:derby://localhost:1527/MotorPartShopDB
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at motorpartshopsoftware.LoginPage.<init>(LoginPage.java:34)
	at motorpartshopsoftware.MotorPartShopSoftware.main(MotorPartShopSoftware.java:19)
```

I am new to java and it would relly helpful if you could solve this.

**Comment by mohite-abhi** [comment]
no solution found
